name: CI/CD Imovel-api

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - name: Install
        run: cd imovel-api && npm install

      - name: Build
        run: cd imovel-api && npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - name: Install
        run: cd imovel-api && npm install

      - name: Test
        run: cd imovel-api && npm run test:cov

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ingaia-imovel-api"
          heroku_email: "wallace.reetz@gmail.com"
          branch: "main"
          appdir: "imovel-api"
